### ISSUE TITLE
Use explicit port number

### ISSUE THREAD

**Issue by mrvanes** [jwijenbergh/eduoauth-go#1]
Are you sure you want to listen port 0 (any?) instead of explicitly specify this as 80 or 8080 e.g?
https://github.com/jwijenbergh/eduoauth-go/blob/1e5d1c810d358a4b3e5e8b02bd1f60a74f8e4491/oauth.go#LL80C14-L80C46

**Comment by jwijenbergh** [comment]
With any do you mean all? Port 0 does not specify all, it specifies a single, available port https://pkg.go.dev/net#Listen. Hard coding a port is not possible because it must be available. See also https://www.ietf.org/archive/id/draft-ietf-oauth-v2-1-07.html#section-8.4.2 for a good description

**Comment by mrvanes** [comment]
Aha, I see and this port will automagically be used in the authn flow later?

**Comment by jwijenbergh** [comment]
> Aha, I see and this port will automagically be used in the authn flow later?

Indeed, see (for the redirect URI) https://github.com/jwijenbergh/eduoauth-go/blob/1e5d1c810d358a4b3e5e8b02bd1f60a74f8e4491/oauth.go#L189 and https://github.com/jwijenbergh/eduoauth-go/blob/1e5d1c810d358a4b3e5e8b02bd1f60a74f8e4491/oauth.go#L468

The listener is configured in the local server here

https://github.com/jwijenbergh/eduoauth-go/blob/1e5d1c810d358a4b3e5e8b02bd1f60a74f8e4491/oauth.go#L113

Thanks for the issue!
